// Generated by CoffeeScript 1.6.3
(function() {
  var createActionMoveTo, deffendingY, disconnected, getWantedBarrelPos, isEqualPos, joinSimulation, manhattanDistanceOne, myTeam, net, opponentTeam, runTurn, server, simulationId, targetY;

  net = require("net");

  simulationId = process.argv[2] != null ? process.argv[2] : null;

  server = null;

  disconnected = false;

  targetY = 0;

  deffendingY = 0;

  myTeam = "";

  opponentTeam = "";

  getWantedBarrelPos = function(barrelPos, wantedY) {
    return {
      x: barrelPos.x,
      y: barrelPos.y > wantedY ? barrelPos.y + 1 : barrelPos.y - 1
    };
  };

  manhattanDistanceOne = function(pos1, pos2) {
    var distanceX, distanceY;
    distanceX = pos1.x - pos2.x;
    console.log(pos1.x);
    console.log(pos1.y);
    distanceY = pos1.y - pos2.y;
    distanceX = (distanceX >= 0) != null ? distanceX : 0 - distanceX;
    distanceY = (distanceY >= 0) != null ? distanceY : 0 - distanceY;
    return distanceX + distanceY === 1;
  };

  isEqualPos = function(pos1, pos2) {
    return pos1.x === pos2.x && pos1.y === pos2.y;
  };

  createActionMoveTo = function(bot, toPosition, toEvit) {
    var direction;
    if (bot.coords.y < toPosition.y && !isEqualPos(toEvit, {
      x: bot.coords.x,
      y: bot.coords.y + 1
    })) {
      direction = "SOUTH";
    }
    if (bot.coords.y > toPosition.y && !isEqualPos(toEvit, {
      x: bot.coords.x,
      y: bot.coords.y - 1
    })) {
      direction = "NORTH";
    }
    if (bot.coords.x < toPosition.x && !isEqualPos(toEvit, {
      x: bot.coords.x + 1,
      y: bot.coords.y
    })) {
      direction = "EAST";
    }
    if (bot.coords.x > toPosition.x && !isEqualPos(toEvit, {
      x: bot.coords.x - 1,
      y: bot.coords.y
    })) {
      direction = "WEST";
    }
    if (direction != null) {
      return {
        botId: bot.id,
        type: "MOVE",
        direction: direction
      };
    } else {
      return {
        botId: bot.id,
        type: "PASS"
      };
    }
  };

  runTurn = function(state) {
    var actions, attackerBotLogic, attackers, bot, defenderBotLogic, defenders, myTeamBarrel, opponentBarrel, opponents, protectBarrelLogic, turnMessage, _i, _j, _len, _len1;
    myTeamBarrel = state["barrels"][myTeam]["coords"];
    opponentBarrel = state["barrels"][opponentTeam]["coords"];
    opponents = state[opponentTeam];
    attackers = [];
    defenders = [];
    actions = [];
    protectBarrelLogic = function(bot, barrel, opponents) {
      var opponent, push, _i, _len;
      if (manhattanDistanceOne(bot, barrel)) {
        push = False;
        for (_i = 0, _len = opponents.length; _i < _len; _i++) {
          opponent = opponents[_i];
          push = push || manhattanDistanceOne(opponent.coords, barrel);
        }
        return push;
      }
    };
    attackerBotLogic = function(bot) {
      var wantedPos;
      wantedPos = getWantedBarrelPos(opponentBarrel, targetY);
      if (protectBarrelLogic(bot, myTeamBarrel)) {
        return actions.push(createActionMoveTo(bot, myTeamBarrel));
      } else if (protectBarrelLogic(bot, opponentBarrel)) {
        return actions.push(createActionMoveTo(bot, opponentBarrel));
      } else if (isEqualPos(bot.coords, wantedPos)) {
        return actions.push(createActionMoveTo(bot, {
          x: bot.coords.x,
          y: targetY
        }, {
          x: -1,
          y: -1
        }));
      } else {
        return actions.push(createActionMoveTo(bot, wantedPos, opponentBarrel));
      }
    };
    defenderBotLogic = function(bot) {
      var wantedPos;
      wantedPos = getWantedBarrelPos(myTeamBarrel, deffendingY);
      if (protectBarrelLogic(bot, myTeamBarrel, opponents)) {
        return actions.push(createActionMoveTo(bot, myTeamBarrel));
      } else if (protectBarrelLogic(bot, opponentBarrel, opponents)) {
        return actions.push(createActionMoveTo(bot, opponentBarrel));
      } else if (isEqualPos(bot.coords, wantedPos)) {
        return actions.push(createActionMoveTo(bot, {
          x: bot.coords.x,
          y: deffendingY
        }, {
          x: -1,
          y: -1
        }));
      } else {
        return actions.push(createActionMoveTo(bot, wantedPos, myTeamBarrel));
      }
    };
    attackers = [state[myTeam][0], state[myTeam][2], state[myTeam][4]];
    defenders = [state[myTeam][1], state[myTeam][3]];
    for (_i = 0, _len = attackers.length; _i < _len; _i++) {
      bot = attackers[_i];
      attackerBotLogic(bot);
    }
    for (_j = 0, _len1 = defenders.length; _j < _len1; _j++) {
      bot = defenders[_j];
      defenderBotLogic(bot);
    }
    turnMessage = {
      type: "player-turn",
      actions: actions
    };
    if (!disconnected) {
      return server.write(JSON.stringify(turnMessage));
    }
  };

  joinSimulation = function() {
    return server.write(JSON.stringify({
      simulationId: simulationId,
      type: "join-simulation",
      nick: "Dummy",
      names: ["Carawebo", "Pantuflo", "Chistaburras", "Pontato", "Jhonny Tablas"]
    }));
  };

  server = net.connect({
    port: 9000
  }, joinSimulation);

  server.on("data", function(data) {
    var message;
    message = JSON.parse(data);
    switch (message["type"]) {
      case "game-info":
        myTeam = message["team"];
        if (myTeam === "team1") {
          targetY = message["height"];
          deffendingY = message["height"];
          return opponentTeam = "team2";
        } else {
          targetY = 0;
          deffendingY = 0;
          return opponentTeam = "team1";
        }
        break;
      case "ready":
        simulationId = message["simulationId"];
        return joinSimulation();
      case "turn":
        return runTurn(message["state"]);
      case "score":
        return console.log("SCORE");
      case "error":
        if (message["message"] === "Player disconnected") {
          console.log;
        }
        if (message["message"] === "Wrong simulation ID") {
          return server.write(JSON.stringify({
            type: "create-simulation"
          }));
        }
        break;
      default:
        return server.end();
    }
  });

  server.on("end", function() {
    disconnected = true;
    return console.log("END");
  });

}).call(this);
